language: ruby
before_script:
  - psql -c 'create database kinship_test' -U postgres
  - psql -c "CREATE USER kinship_test WITH CREATEDB PASSWORD 'kinship';" -U postgres
script:
  - bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec slim-lint .
