default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kinship_development

test:
  <<: *default
  database: kinship_test

production:
  <<: *default
  database: kinship_production
  username: kinship
  password: <%= ENV['KINSHIP_DATABASE_PASSWORD'] %>
